image:
  repository: mrdrprof/gitops-assignment
  tag: 123
deployment:
  labels: gitops-assignment
  selector: gitops-assignment
service:
  name: srv-gitops-assignment
  type: LoadBalancer
  selector: gitops-assignment
  port: 80
  targetPort: 8080
